// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using piano_store.Data;

#nullable disable

namespace pianostore.Migrations
{
    [DbContext(typeof(PianoStoreDbContext))]
    [Migration("20231202155027_ShoppingCartItemAdded")]
    partial class ShoppingCartItemAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("piano_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = true,
                            Name = "Piano 1",
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = true,
                            Name = "Piano 2",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = true,
                            Name = "Piano 3",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = false,
                            Name = "Piano 4",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = false,
                            Name = "Piano 5",
                            Price = 15m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = false,
                            Name = "Piano 6",
                            Price = 15m
                        },
                        new
                        {
                            Id = 7,
                            Detail = "Some details",
                            ImageUrl = "",
                            IsTrendingProduct = false,
                            Name = "Piano 7",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("piano_store.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("piano_store.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("piano_store.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
